'use client'

import { COLORS, getSharedStyles, usePersistedTheme, BRAND_GRADIENT } from '@/lib/theme'
import Nav from '@/components/Nav'
import { useLanguage } from '@/lib/i18n/context'

// ─────────────────────────────────────────────────────────────────────────
// Download page — direct APK distribution (not Google Play).
//
// The APK itself lives at /public/downloads/quality-hub.apk. It is NOT
// generated by this app — it's built separately via Bubblewrap and must be
// manually placed there (and replaced there on every future Bubblewrap
// rebuild, e.g. after switching to the qualityhub.tools domain or updating
// icons/branding). See docs/ or the TWA setup notes for the build steps.
// ─────────────────────────────────────────────────────────────────────────

const APK_PATH = '/downloads/quality-hub.apk'

export default function DownloadPage() {
  const [theme, setTheme] = usePersistedTheme()
  const { t } = useLanguage()
  const c = COLORS[theme]
  const s = getSharedStyles(theme)
  const dark = theme === 'dark'

  const bodyColor = dark ? 'rgba(226,232,240,0.82)' : 'rgba(30,41,59,0.82)'

  const sectionHeading: React.CSSProperties = {
    fontSize: 19,
    fontWeight: 800,
    color: c.text,
    margin: '0 0 14px',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  }
  const headingBar: React.CSSProperties = {
    width: 4,
    height: 18,
    borderRadius: 2,
    background: c.accent,
    flexShrink: 0,
  }
  const paragraph: React.CSSProperties = {
    fontSize: 15,
    color: bodyColor,
    lineHeight: 1.85,
    margin: '0 0 16px',
  }

  const steps = [
    { title: t('download_step1_title'), desc: t('download_step1_desc') },
    { title: t('download_step2_title'), desc: t('download_step2_desc') },
    { title: t('download_step3_title'), desc: t('download_step3_desc') },
  ]

  return (
    <div style={s.page}>
      <Nav theme={theme} setTheme={setTheme} breadcrumbKey="bc_download" showGetPro={false} />

      <main className="qh-main" style={{ ...s.main, alignItems: 'center' }}>
        <div style={{ maxWidth: 720, width: '100%', marginTop: 20 }}>
          {/* ── Hero ── */}
          <div style={{ textAlign: 'center', marginBottom: 36 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: c.accent, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 12 }}>
              {t('download_kicker')}
            </div>
            <h1 style={{ fontSize: 34, fontWeight: 800, color: c.text, margin: '0 0 14px', lineHeight: 1.28, letterSpacing: -0.5 }}>
              {t('download_hero_title')}
            </h1>
            <p style={{ ...paragraph, maxWidth: 520, margin: '0 auto' }}>
              {t('download_hero_sub')}
            </p>
          </div>

          {/* ── Download CTA ── */}
          <section style={{ ...s.card, marginBottom: 28, padding: 32, textAlign: 'center' }}>
            <a
              href={APK_PATH}
              download
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 10,
                background: BRAND_GRADIENT,
                color: '#ffffff',
                fontSize: 15,
                fontWeight: 700,
                padding: '14px 28px',
                borderRadius: 10,
                textDecoration: 'none',
                boxShadow: `0 8px 24px ${c.accent}40`,
              }}
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              {t('download_btn')}
            </a>
            <div style={{ fontSize: 12.5, color: c.muted, marginTop: 12 }}>
              {t('download_size_note')}
            </div>
          </section>

          {/* ── Why an app ── */}
          <section style={{ marginBottom: 36 }}>
            <h2 style={sectionHeading}>
              <span style={headingBar} />
              {t('download_why_heading')}
            </h2>
            <p style={{ ...paragraph, marginBottom: 0 }}>
              {t('download_why_p')}
            </p>
          </section>

          {/* ── How to install ── */}
          <section style={{ ...s.card, marginBottom: 24, padding: 28 }}>
            <h2 style={sectionHeading}>
              <span style={headingBar} />
              {t('download_steps_heading')}
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
              {steps.map((step, i) => (
                <div key={step.title} style={{ display: 'flex', gap: 14 }}>
                  <div
                    style={{
                      flexShrink: 0,
                      width: 28,
                      height: 28,
                      borderRadius: '50%',
                      background: `${c.accent}16`,
                      border: `1px solid ${c.accent}55`,
                      color: c.accent,
                      fontSize: 13,
                      fontWeight: 800,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    {i + 1}
                  </div>
                  <div>
                    <div style={{ fontSize: 14.5, fontWeight: 700, color: c.text, marginBottom: 3 }}>
                      {step.title}
                    </div>
                    <div style={{ fontSize: 13.5, color: bodyColor, lineHeight: 1.7 }}>
                      {step.desc}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* ── iOS note ── */}
          <div
            style={{
              fontSize: 13,
              color: c.muted,
              textAlign: 'center',
              padding: '14px 18px',
              borderRadius: 10,
              background: c.surface2,
              border: `1px solid ${c.border}`,
              marginBottom: 20,
            }}
          >
            {t('download_ios_note')}
          </div>
        </div>
      </main>
    </div>
  )
}
